name: Purge old artifacts

on:
  workflow_dispatch:   # manuell startbar
  schedule:
    - cron: "0 3 * * 0"   # jeden Sonntag 03:00 UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts (>7 Tage)
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            const now = new Date();

            for (const artifact of data.artifacts) {
              const created = new Date(artifact.created_at);
              const ageDays = Math.floor((now - created) / (1000 * 60 * 60 * 24));

              if (ageDays > 7) {
                console.log(`🗑 Lösche: ${artifact.name} (${artifact.id}), ${ageDays} Tage alt`);
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
              } else {
                console.log(`✅ Behalte: ${artifact.name} (${artifact.id}), nur ${ageDays} Tage alt`);
              }
            }
